environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 7.9.0 x64
  - npm install -g npm@4 --silent

build_script:
  - .\scripts\npm.bat install
  - .\node_modules\.bin\gulp electron
  - npm run compile

test_script:
  - node --version
  - npm --version
  - .\scripts\test.bat
  - .\scripts\test-integration.bat
